artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: http://download.tensorflow.org/example_images/flower_photos.tgz
  local_data_file: artifacts/data_ingestion/data.tgz
  unzip_dir: artifacts/data_ingestion